# Generated by Django 5.0.1 on 2024-02-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyproducts',
            name='customer_id',
        ),
    ]
