# Generated by Django 5.0.1 on 2024-02-14 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='product_image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='product_image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='product_image6',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='product_image7',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products_images/'),
            preserve_default=False,
        ),
    ]
