# Generated by Django 5.0.1 on 2024-02-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_warrantyproducts_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='telephone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.BigIntegerField(),
        ),
    ]
